'use client'

import { Calendar } from '@/components/Calendar'
import { DateTime } from '@/utils/types'
import { type NextPage } from 'next'
import Head from 'next/head'
import { useState } from 'react'

const Home: NextPage = () => {
  const [date, setDate] = useState<DateTime>({
    justDate: null,
    dateTime: null,
  })

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Calendar setDate={setDate} date={date} />
      </main>
    </>
  )
}

export default Home
