'use client'

import { Calendar } from '@/components/Calendar'
import Spinner from '@/components/Spinner'
import { DateTime } from '@/utils/types/types'
import { type NextPage } from 'next'
import Head from 'next/head'
import { useState } from 'react'

const Home: NextPage = () => {
  const [date, setDate] = useState<DateTime>({
    justDate: null,
    dateTime: null,
  })

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {!date.dateTime && <Calendar setDate={setDate} date={date} />}
        {date.dateTime && true ? (
          // <Menu />
          <h1>Menu</h1>
        ) : (
          <div className="flex h-screen items-center justify-center">
            <Spinner />
          </div>
        )}
      </main>
    </>
  )
}

export default Home
